### ISSUE TITLE
add ci pipeline to autmatically run tests and publish library

### ISSUE THREAD

**Issue by wendellmva** [wendellmva/tinytools#1]
## tasks

- [x] use gitflow for new features
- [x] script to run tests
- [x] script to version .net library
- [x] script to tag and release a new version
- [x] script to publish to nuget and github
