### ISSUE TITLE
add support for more named parameters

### ISSUE THREAD

**Issue by wendellmva** [wendellmva/tinytools#2]
## tasks

- [ ] add support for dictionaries
- [ ] add support for ienumerable
- [ ] add support for local variables
- [ ] add support for static consts
- [ ] add support for enums
