### ISSUE TITLE
find and replace in paths and text

### ISSUE THREAD

**Issue by wendellmva** [wendellmva/tinytools#3]
# Tasks

- [ ] add method to find string and to replace it with string
- [ ] allow for case sensitives finds
- [ ] add cli method to run from the command line
